 on:
  workflow_call:
    outputs:
      semver: 
        value: ${{ jobs.generate-semver.outputs.semver }}
      build-semver:
        value: ${{ jobs.generate-semver.outputs.build-semver }}
    
jobs:
  generate-semver:
    runs-on: ubuntu-latest
    outputs:
      semver: ${{ steps.semver.outputs.version }} # needs to be improved (maybe simply use a single semver variable, but use a different format based on branch e.g., main vs dev vs feature branch)
      build-semver: ${{ steps.build-semver.outputs.semver }}
    steps:
      - name: ✅ Checkout
        uses: actions/checkout@v3

      - name: ⚙️ Generate SemVersion
        id: semver
        uses: paulhatch/semantic-version@v5.3.0

      - name: ⚙️ Generate build SemVersion 
        id: build-semver
        run: |
          echo "semver=${{ steps.semver.outputs.version }}-${{ github.run_id }}.${{ github.run_attempt }}" >> "$GITHUB_OUTPUT"
